In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [8]:
# converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## year

In [10]:
date['date_year'] = date['date'].dt.year

In [11]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

## month

In [ ]:
date['date_month'] = date['date'].dt.month

In [18]:
date['date_month_name'] = date['date'].dt.month_name()

In [20]:
date['date_day'] = date['date'].dt.day

In [21]:
date['date_day_name'] = date['date'].dt.day_name()

In [26]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_day_name,date-dow-name,date_dow
0,2019-12-10,5628,25,3,2019,12,10,December,Tuesday,Tuesday,1
1,2018-08-15,3646,14,157,2018,8,15,August,Wednesday,Wednesday,2
2,2018-10-23,1859,25,1,2018,10,23,October,Tuesday,Tuesday,1
3,2019-08-17,7292,25,1,2019,8,17,August,Saturday,Saturday,5
4,2019-01-06,4344,25,3,2019,1,6,January,Sunday,Sunday,6

In [ ]:
# date = date.drop(columns='date-dow-name')

In [30]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_day_name,date_dow
0,2019-12-10,5628,25,3,2019,12,10,December,Tuesday,1
1,2018-08-15,3646,14,157,2018,8,15,August,Wednesday,2
2,2018-10-23,1859,25,1,2018,10,23,October,Tuesday,1
3,2019-08-17,7292,25,1,2019,8,17,August,Saturday,5
4,2019-01-06,4344,25,3,2019,1,6,January,Sunday,6

## Week of the year

In [40]:
date['date_week'] = date['date'].dt.week

date.head()

AttributeError: 'DatetimeProperties' object has no attribute 'week'

## Extract quarter

In [43]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_day,date_month_name,date_day_name,date_dow,date_week,quarter
0,2019-12-10,2019,12,10,December,Tuesday,1,1,4
1,2018-08-15,2018,8,15,August,Wednesday,2,2,3
2,2018-10-23,2018,10,23,October,Tuesday,1,1,4
3,2019-08-17,2019,8,17,August,Saturday,5,5,3
4,2019-01-06,2019,1,6,January,Sunday,6,6,1

In [44]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_day,date_month_name,date_day_name,date_dow,date_week,quarter,semester
0,2019-12-10,2019,12,10,December,Tuesday,1,1,4,2
1,2018-08-15,2018,8,15,August,Wednesday,2,2,3,2
2,2018-10-23,2018,10,23,October,Tuesday,1,1,4,2
3,2019-08-17,2019,8,17,August,Saturday,5,5,3,2
4,2019-01-06,2019,1,6,January,Sunday,6,6,1,1

Extract Time elapsed between dates

In [45]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 3, 17, 14, 53, 4, 323498)

In [46]:
today - date['date']

0     2289 days 14:53:04.323498
1     2771 days 14:53:04.323498
2     2702 days 14:53:04.323498
3     2404 days 14:53:04.323498
4     2627 days 14:53:04.323498
                 ...
995   2717 days 14:53:04.323498
996   2658 days 14:53:04.323498
997   2506 days 14:53:04.323498
998   2571 days 14:53:04.323498
999   2345 days 14:53:04.323498
Name: date, Length: 1000, dtype: timedelta64[ns]

In [48]:
(today - date['date']).dt.days

0      2289
1      2771
2      2702
3      2404
4      2627
       ...
995    2717
996    2658
997    2506
998    2571
999    2345
Name: date, Length: 1000, dtype: int64

## Time

In [53]:
# converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [54]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [55]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [56]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [57]:
today - time['date']

0     4475 days 14:03:04.323498
1     4339 days 15:13:04.323498
2     4825 days 14:32:04.323498
3     4127 days 14:22:04.323498
4     4524 days 15:42:04.323498
                 ...
995   5114 days 14:03:04.323498
996   4435 days 15:39:04.323498
997   4900 days 15:16:04.323498
998   5016 days 15:19:04.323498
999   4288 days 15:28:04.323498
Name: date, Length: 1000, dtype: timedelta64[ns]